import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import fetch from "node-fetch";
import {
  SSRProvider,
  Provider,
  defaultTheme,
  Grid,
  View,
  repeat
} from "@adobe/react-spectrum";
import { today } from "@internationalized/date";
import clientPromise from "../mongodb";
import { OptionsPicker } from "../components/OptionsPicker";
import { timeZones } from "../components/utils.js";
import { FixtureTable } from "../components/FixtureTable";
import { Quicksort } from "../components/Quicksort";

function findFixtureRange(array, date) {
  var low = 0,
    high = array.dataSet.length;

  while (low < high) {
    var mid = (low + high) >>> 1;
    var tempDate = new Date(array.dataSet[mid].fixture.date);
    if (tempDate < date) low = mid + 1;
    else high = mid;
  }
  return low;
}

function sortByDates(fixtureArray, fixture, venueArray) {
  var low = 0,
    high = fixtureArray.length,
    date = new Date(fixture.fixture.date);

  while (low < high) {
    var mid = (low + high) >>> 1;
    var tempDate = new Date(fixtureArray[mid].fixture.date);
    if (tempDate < date) low = mid + 1;
    else high = mid;
  }
  fixtureArray.splice(low, 0, fixture);
  venueArray.splice(low, 0, fixture.fixture.venue.id);
}

export async function getServerSideProps({
  query: {
    startDate = today(),
    endDate = today().add({ weeks: 2 }),
    leagueArr = ["39"]
  }
}) {
  if (typeof leagueArr === "string") {
    leagueArr = leagueArr.split(",");
  }
  const league = "41";
  const season = "2022";
  const leagueName = "league-" + league;

  const client = await clientPromise;
  const db = client.db("football_advisor");
  const coll = await db.collection("fixtures");

  const rawData = await db
    .collection("fixtures")
    .find({ leagueId: { $in: leagueArr } })
    .toArray();

  let footballData = [];
  let venueArray = [];
  let leagueStartDate = new Date(startDate);
  let leagueEndDate = new Date(endDate);

  for (let i = 0; i < rawData.length; i++) {
    let startingFixture = findFixtureRange(rawData[i], leagueStartDate);
    let endingFixture = findFixtureRange(rawData[i], leagueEndDate);
    for (let j = startingFixture; j < endingFixture; j++) {
      sortByDates(footballData, rawData[i].dataSet[j], venueArray);
    }
  }

  //console.log(venueArray);
  
  var query = [
    {$match: {"id": {$in: venueArray}}},
    {$addFields: {"__venueData": {$indexOfArray: [venueArray, "$id" ]}}},
    {$sort: {"__venueData": 1}}
   ];

  const venues = await db.collection("top_venues").aggregate( query ).toArray();
  
  /*
  for (let i = 0; i < venues.length; i++) {
    console.log(venues[i].id);
  }
  */
  
  let venueData = JSON.stringify(venues);

  return {
    props: {
      footballData,
      venueData
    }
  };
}

export default function Home({ footballData, venueData }) {
  return (
    <SSRProvider>
      <Provider theme={defaultTheme} colorScheme="dark">
        <div className={styles.container}>
          <Head>
            <title>Football Advisor</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>Welcome to Football Advisor</h1>

            <div className={styles.pickerGrid}>
              <OptionsPicker />

              <FixtureTable footballData={footballData} venueData={venueData}/>

            </div>
          </main>

          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </div>
      </Provider>
    </SSRProvider>
  );
}
